name: Update DB

on:
  schedule:
    - cron: '50 22 * * *'

jobs:
  browserlist-db:
    runs-on: ubuntu-latest
    env:
      GH_BROWSERLIST_BRANCH: update-browserlist-db
    name: Updates the browserlist db
    steps:
      - uses: hmarr/debug-action@v2

      - name: ⬇️ Checkout
        uses: actions/checkout@v2

      - name: Read NodeJS version from .nvmrc
        id: node-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.nvmrc
          trim: true

      - name: Setup NodeJS using the obtained nvm version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.outputs.content }}

      - name: Restore cached node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: ▶️ Install Dependencies
        run: npm i

      - name: Create a branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.GH_BROWSERLIST_BRANCH }}

      - name: 🚀 Run the update-db command
        run: npx browserslist@latest --update-db

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'package-lock.json'
          branch: update-browserlist-db
          branch_mode: create
          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: github_actions
          message: 'perf(browserlist): Deliver the Browserslist DB update'
          pull: 'NO-PULL'
          push: origin ${{ env.GH_BROWSERLIST_BRANCH }} --force

      - name: 🏗 Create Pull-Request into dist branch
        #        if: steps.auto-commit.outputs.changes_detected == 'true'
        uses: repo-sync/pull-request@v2
        with:
          pr_title: 'perf(browserlist): Deliver the Browserslist DB update'
          pr_body: ':crown: *An automated PR from the Browserlist workflow*'
          source_branch: ${{ env.GH_BROWSERLIST_BRANCH }}
          destination_branch: ${{ env.GITHUB_REF_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
#      - name: Log a message there is anything to commit
#        if: steps.auto-commit.outputs.changes_detected == 'true'
#        run: echo 'There is a browserlist update'
#
#      - name: Log a message if nothing to commit
#        if: steps.auto-commit.outputs.changes_detected == 'false'
#        run: echo 'Everything is up to date'
