name: Deployer

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GH_RELEASE_BRANCH: release-branch
      GH_OUTPUT_BRANCH: master

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node using nvm
        uses: dcodeIO/setup-node-nvm@v4.0.0

      - name: Install Dependencies
        run: npm ci

      - name: Build project
        run: npm run build:root

      - name: Set github username
        run: git config user.name ${{ secrets.GH_AUTHOR_LOGIN }}

      - name: Set github email
        run: git config user.email ${{ secrets.GH_AUTHOR_EMAIL }}

      - name: Fetch git tree
        run: git fetch --all

      - name: Create release branch
        run: git checkout -b $GH_RELEASE_BRANCH $GH_OUTPUT_BRANCH

      - name: Add files into version control
        run: git add .

      - name: Commit release files
        run: git commit -m "Deliver new application release"

      - name: Push changes into branch
        run: git push --force --set-upstream origin $GH_RELEASE_BRANCH
