name: Validate PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  preview:
    runs-on: ubuntu-latest
    name: Deploy to sandbox
    environment: Preview
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS using the obtained nvm version
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: ${{ secrets.KOYEB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Deploy to Koyeb
#        run: koyeb service redeploy blog/n0th1ng-else-blog
