name: Validate

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Validate the code
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node using nvm
        uses: dcodeIO/setup-node-nvm@v4.0.0

      - name: Install Dependencies
        run: npm ci

      - name: Validate the project
        run: npm run validate
