name: Validate

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Validate the code
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node using nvm
        uses: dcodeIO/setup-node-nvm@v4

      - name: Restore cached node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: npm ci

      - name: Validate the project
        run: npm run validate

      - name: Lint the project
        run: npm run lint:all

      - name: Check the formatting in the project
        run: npm run format:check
